project:
  type: website
  resources:
    - robots.txt
  output-dir: docs

website:
  title: "Bradford Johnson"
  site-url: 'https://ford-johnson.com/'
  
  google-analytics: "G-1BB9B4C1GN"
  
  favicon: "visuals/favicon.png"
  navbar:
    background: light
    title: false
    left:
      - href: index.qmd
        text: Home
      #- projects/index.qmd
    right:
      - icon: linkedin
        href: https://linkedin.com/in/bradford-ford-johnson
      - icon: github
        href: https://github.com/bradfordjohnson
  page-footer:
    left: "Created by [Bradford Johnson](https://github.com/bradfordjohnson) © 2024"

format:
  html:
    theme: ["_variables.scss", default]
    toc: true
    link-external-newwindow: true
