project:
  type: website
  # resources:
    # - hello-framework/dist/
  output-dir: docs

website:
  title: "Ford Johnson"
  site-url: 'https://ford-johnson.com/'
  google-analytics: "G-1BB9B4C1GN"
  favicon: "/assets/favicon.png"
  navbar:
    background: dark
    pinned: true
    left: 
      - text: Home
        href: index.qmd

      - text: Gallery
        href: gallery/index.qmd

      # - text: Projects 
      #   href: projects/index.qmd

      - text: Notes
        href: notes/index.qmd
    right:
      - icon: github
        href: https://github.com/bradfordjohnson/portfolio
format:
  html:
    theme: [cosmo.scss]
    css: styles.css
    link-external-newwindow: true



